### ISSUE TITLE
java.lang.NullPointerException: ImagePipelineFactory was not initialized!

### ISSUE THREAD

**Issue by bobowg** [bobowg/BaiseComposeLearn#10]
Process: com.example.baisecomposelearn, PID: 11211
    java.lang.NullPointerException: ImagePipelineFactory was not initialized!
        at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:227)
        at com.facebook.imagepipeline.core.ImagePipelineFactory.getInstance(ImagePipelineFactory.java:70)
        at com.facebook.drawee.backends.pipeline.Fresco.getImagePipelineFactory(Fresco.java:140)
        at com.facebook.drawee.backends.pipeline.Fresco.getImagePipeline(Fresco.java:145)
        at com.skydoves.landscapist.fresco.FrescoImage__FrescoImageKt.FrescoImage$FrescoImage__FrescoImageKt(FrescoImage.kt:497)
        at com.skydoves.landscapist.fresco.FrescoImage__FrescoImageKt.FrescoImage(FrescoImage.kt:400)
        at com.skydoves.landscapist.fresco.FrescoImage.FrescoImage(FrescoImage.kt:1)
        at com.skydoves.landscapist.fresco.FrescoImage__FrescoImageKt.FrescoImage(FrescoImage.kt:105)
        at com.skydoves.landscapist.fresco.FrescoImage.FrescoImage(FrescoImage.kt:1)
        at com.example.baisecomposelearn.screens.media.FrescoLandscapistScreenKt.FrescoLandscapistScreen(FrescoLandscapistScreen.kt:17)

**Comment by bobowg** [comment]
java.lang.NullPointerException: ImagePipelineFactory was not initialized! 图片没有初始化，初始化图片即可 ！
