### ISSUE TITLE
Installation did not succeed. The application could not be installed. 程序运行不了

### ISSUE THREAD

**Issue by bobowg** [bobowg/BaiseComposeLearn#7]
Installation did not succeed.
The application could not be installed.

List of apks:
[0] '/media/bobo/learn/Phone/BaiseComposeLearn/app/build/intermediates/apk/debug/app-debug.apk'
Installation failed due to: ''cmd package install-create -r -t --user current --full --dont-kill --skip-verification -S 15272961' returns error 'Unknown failure: Exception occurred while executing 'install-create':
android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space
at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:595)
at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:3434)
at com.android.server.pm.PackageManagerShellCommand.runInstallCreate(PackageManagerShellCommand.java:1561)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:232)
at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
at android.os.ShellCommand.exec(ShellCommand.java:38)
at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:5954)
at android.os.Binder.shellCommand(Binder.java:1049)
at android.os.Binder.onTransact(Binder.java:877)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4313)
at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:5938)
at android.os.Binder.execTransactInternal(Binder.java:1285)
at android.os.Binder.execTransact(Binder.java:1244)
Caused by: java.io.IOException: Requested internal only, but not enough space
at com.android.internal.content.InstallLocationUtils.resolveInstallVolume(InstallLocationUtils.java:241)
at com.android.internal.content.InstallLocationUtils.resolveInstallVolume(InstallLocationUtils.java:152)
at com.android.internal.content.InstallLocationUtils.resolveInstallVolume(InstallLocationUtils.java:167)
at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:803)
at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:592)
... 12 more''
Retry
Failed to launch an application on all devices

**Comment by bobowg** [comment]
参考https://www.techypid.com/the-application-could-not-be-installed/重启模拟器
